### ISSUE TITLE
problem of running the code

### ISSUE THREAD

**Issue by zsdonghao** [avisingh599/imitation-dagger#2]
Hi, first of all, many thanks for your great work.

I got a problem and don't know whether it is caused by torcs' update or my misunderstanding.

- If I simply run `python dagger.py`, I will get `Timeout for client answer`.
- If I set up the server on another terminal and initialize the game as shown in [gym_torcs](https://github.com/ugo-nama-kun/gym_torcs), then when I run `python dagger.py`, I will got this:

```
cannot bind socketClient connected on 3101..............
Traceback (most recent call last):
  File "dagger.py", line 30, in <module>
    ob = env.reset(relaunch=True)
  File "/home/hao/Workspace/imitation-dagger/gym_torcs.py", line 190, in reset
    self.observation = self.make_observaton(obs)
  File "/home/hao/Workspace/imitation-dagger/gym_torcs.py", line 270, in make_observaton
    image_rgb = self.obs_vision_to_image_rgb(raw_obs[names[8]])
KeyError: 'img'
```

Thanks in advance.

**Comment by avisingh599** [comment]
Yes, I think the server needs to be started first. Have you tried resizing the TORCS window to 64x64 before you run `python dagger.py`?
